ERROR -> 2024-04-17 14:52:38,584 -> log -> log.py -> Internal Server Error: /api/v1/hotel/hotel
Traceback (most recent call last):
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/middleware/common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/api/v1/hotel/hotel/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR -> 2024-04-18 13:43:22,450 -> log -> log.py -> Internal Server Error: /api/v1/account/login
Traceback (most recent call last):
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/middleware/common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/api/v1/account/login/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR -> 2024-04-18 13:44:41,068 -> log -> log.py -> Internal Server Error: /api/v1/comments/
Traceback (most recent call last):
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 208, in save
    self.instance = self.create(validated_data)
  File "/home/shade/Desktop/py32/Airbnb_proj/hotel/serializers.py", line 50, in create
    hotel = Hotel.objects.get(slug=validated_data['hotel'])
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
hotel.models.Hotel.DoesNotExist: Hotel matching query does not exist.
ERROR -> 2024-04-18 14:34:29,338 -> log -> log.py -> Internal Server Error: /api/v1/favorites/
Traceback (most recent call last):
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "hotel_favorites" does not exist
LINE 1: INSERT INTO "hotel_favorites" ("author_id", "hotel_id") VALU...
                    ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 208, in save
    self.instance = self.create(validated_data)
  File "/home/shade/Desktop/py32/Airbnb_proj/hotel/serializers.py", line 51, in create
    return super().create(validated_data)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 989, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "hotel_favorites" does not exist
LINE 1: INSERT INTO "hotel_favorites" ("author_id", "hotel_id") VALU...
                    ^

ERROR -> 2024-04-19 13:36:55,299 -> log -> log.py -> Internal Server Error: /api/v1/account/login
Traceback (most recent call last):
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/middleware/common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
  File "/home/shade/Desktop/py32/Airbnb_proj/venv/lib/python3.8/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via PATCH, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining PATCH data. Change your form to point to 127.0.0.1:8000/api/v1/account/login/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
